name: Swagger UI Generator

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: swagger.yaml
      - name: Add a file to the swagger-ui directory
        run: echo "pasteportal.info" > swagger-ui/CNAME
      - name: Add a file to the swagger-ui directory
        run: echo "bananas" > swagger-ui/fruits
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
